spring:
  application:
    name: wirebarley_service
  config:
    activate:
      on-profile: common
  messages:
    basename: messages/messages, messages/error

logging:
  level:
    p6spy: info
    com:
      zaxxer:
        hikari: INFO

mybatis:
  type-aliases-package: com.wirebarley.domain
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

resilience4j.retry:
  configs:
    bankRetryConfig:
      maxAttempts: 3
      waitDuration: 1000
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 5
      retryExceptions:
        - com.wirebarley.global.exception.exception.BankException   # retryExceptions에 지정된 예외는 재시도
    #      ignoreExceptions:
    #        -   # retryExceptions에 지정되지 않은 예외는 ignoreExceptions로 처리됨
  instances:
    bankRetryConfig:
      baseConfig: bankRetryConfig

jwt:
  secretKey: 1234
  refreshKey: 12341234
  signatureAlgorithm: HS256
  accessTokenExpired: 604800
  refreshTokenExpired: 6048000

server:
  port: 8080
  servlet:
    context-path: /api