spring:
  application:
    name: wirebarley_service
  config:
    activate:
      on-profile: common
  messages:
    basename: messages/messages, messages/error

logging:
  level:
    p6spy: info
    com:
      zaxxer:
        hikari: INFO

mybatis:
  type-aliases-package: com.wirebarley.domain
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secretKey: 1234
  refreshKey: 12341234
  signatureAlgorithm: HS256
  accessTokenExpired: 604800
  refreshTokenExpired: 6048000

server:
  port: 8080
  servlet:
    context-path: /api